server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:33061/usuarios
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "921c4095e8f1a1e1242baa08b1cf475dbad416f901e29c53544d1a61eb6622ba"
  expiration: "AUTH0JWT-BACKEND"

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
