server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:33061/usuarios
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: user
      password: 1234

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
